# Generated by Django 3.1.2 on 2020-11-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, default='/static/img/default-user.png', null=True, upload_to='Natural Stones')),
            ],
        ),
    ]
